/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ctm;

import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author harsi
 */
public class amountFrame extends javax.swing.JFrame {

    /**
     * Creates new form amountForm
     */
    public amountFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalAmnt = new javax.swing.JLabel();
        debitButton = new javax.swing.JButton();
        totalAmntVal = new javax.swing.JLabel();
        selectPayment = new javax.swing.JLabel();
        cashButton = new javax.swing.JButton();
        convFees = new javax.swing.JLabel();
        convFeesVal = new javax.swing.JLabel();
        initialAmntVal = new javax.swing.JLabel();
        initialAmnt = new javax.swing.JLabel();
        amountNeeded = new javax.swing.JTextField();
        amountNeed = new javax.swing.JLabel();
        AmntPayTitle = new javax.swing.JLabel();
        lessThan = new javax.swing.JLabel();
        acceptAmount = new javax.swing.JButton();
        selectedCurr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalAmnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalAmnt.setText("Total Amount Due");

        debitButton.setText("Debit");
        debitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitButtonActionPerformed(evt);
            }
        });

        totalAmntVal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        selectPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectPayment.setText("Select Payment Type");

        cashButton.setText("Cash");
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });

        convFees.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convFees.setText("Convenience Fees (2%)");

        convFeesVal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        initialAmntVal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        initialAmnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        initialAmnt.setText("Amount in ");

        amountNeeded.setToolTipText("");
        amountNeeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountNeededActionPerformed(evt);
            }
        });
        amountNeeded.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountNeededKeyTyped(evt);
            }
        });

        amountNeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountNeed.setText("Amount needed in USD");

        AmntPayTitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AmntPayTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AmntPayTitle.setText("ENTER AMOUNT AND SELECT PAYMENT TYPE");

        lessThan.setText("<500");

        acceptAmount.setText("Submit");
        acceptAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalAmnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(convFees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(initialAmnt)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(acceptAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectedCurr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convFeesVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalAmntVal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(initialAmntVal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(AmntPayTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selectPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(debitButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(cashButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(amountNeed, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amountNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lessThan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AmntPayTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountNeed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountNeeded)
                    .addComponent(lessThan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(acceptAmount)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(initialAmnt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initialAmntVal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedCurr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(convFeesVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convFees, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalAmnt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(totalAmntVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(selectPayment)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debitButton)
                    .addComponent(cashButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitButtonActionPerformed
        this.setVisible(false);
        Ctm.debitPay.setVisible(true);
        Ctm.payMeth = "Debit";
    }//GEN-LAST:event_debitButtonActionPerformed

    private void amountNeededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountNeededActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountNeededActionPerformed

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        this.setVisible(false);
        Ctm.cashPay.setVisible(true);
        Ctm.payMeth = "Cash";
    }//GEN-LAST:event_cashButtonActionPerformed

    private void amountNeededKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountNeededKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_amountNeededKeyTyped

    private void acceptAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptAmountActionPerformed
        if (Integer.parseInt(amountNeeded.getText()) > 500) {
            lessThan.setText("Enter a value < 500");
        } else {
            Ctm.usdAmount = Integer.parseInt(amountNeeded.getText());
            Ctm.amount.selectedCurr.setText(Ctm.curr);
            Ctm.initialAmount = (Ctm.excRate) * (Integer.parseInt(amountNeeded.getText()));
            Ctm.amount.initialAmntVal.setText(String.valueOf(Ctm.initialAmount));
            Ctm.fees = (Ctm.initialAmount) * 0.02;
            Ctm.amount.convFeesVal.setText(String.valueOf(Ctm.fees));
            Ctm.total = (Ctm.initialAmount) + (Ctm.fees);
            Ctm.amount.totalAmntVal.setText(String.valueOf(Ctm.total));
            Ctm.cashPay.initialCurrLabel.setText(Ctm.curr);
            Ctm.cashPay.initialAmntCash.setText(String.valueOf(Ctm.total));
            Ctm.cashPay.initialCurrLab.setText(Ctm.curr);
        }
    }//GEN-LAST:event_acceptAmountActionPerformed

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new amountFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmntPayTitle;
    private javax.swing.JButton acceptAmount;
    private javax.swing.JLabel amountNeed;
    public javax.swing.JTextField amountNeeded;
    private javax.swing.JButton cashButton;
    private javax.swing.JLabel convFees;
    public javax.swing.JLabel convFeesVal;
    private javax.swing.JButton debitButton;
    private javax.swing.JLabel initialAmnt;
    public javax.swing.JLabel initialAmntVal;
    private javax.swing.JLabel lessThan;
    private javax.swing.JLabel selectPayment;
    private javax.swing.JLabel selectedCurr;
    private javax.swing.JLabel totalAmnt;
    public javax.swing.JLabel totalAmntVal;
    // End of variables declaration//GEN-END:variables
}
