/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ctm;

import java.util.Random;

/**
 *
 * @author harsi
 */
public class cashPayFrame extends javax.swing.JFrame {

    Random r = new Random();

    /**
     * Creates new form cashPayFrame
     */
    public cashPayFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashReturnVal = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        cashReturned = new javax.swing.JLabel();
        initialAmntCash = new javax.swing.JLabel();
        required = new javax.swing.JLabel();
        cashInsert = new javax.swing.JTextField();
        amountOf = new javax.swing.JLabel();
        cashPayment = new javax.swing.JLabel();
        initialCurrLabel = new javax.swing.JLabel();
        intialAmntCash = new javax.swing.JLabel();
        initialCurrLab = new javax.swing.JLabel();
        submitCashButton = new javax.swing.JButton();
        warningLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        cashReturned.setText("Cash Returned");

        required.setText("Required");

        cashInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashInsertActionPerformed(evt);
            }
        });
        cashInsert.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashInsertKeyTyped(evt);
            }
        });

        amountOf.setText("Amount of");

        cashPayment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cashPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashPayment.setText("CASH PAYMENT");

        intialAmntCash.setText("Inserted");

        submitCashButton.setText("Submit");
        submitCashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCashButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountOf, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(initialCurrLab, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intialAmntCash, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(initialCurrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(required, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(continueButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cashReturned, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                            .addComponent(warningLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(34, 34, 34)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submitCashButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cashInsert)
                                        .addComponent(initialAmntCash, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(cashReturnVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(cashPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(initialAmntCash, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(required, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initialCurrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intialAmntCash, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initialCurrLab, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitCashButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warningLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashReturned, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashReturnVal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(continueButton)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        this.setVisible(false);
        Ctm.transSum.currConvVal.setText(String.valueOf(Ctm.usdAmount));
        Ctm.transSum.excRateVal.setText(String.valueOf(Ctm.excRate));
        Ctm.transSum.initialAmntVal.setText(String.valueOf(Ctm.initialAmount));
        Ctm.transSum.feesVal.setText(String.valueOf(Ctm.fees));
        Ctm.transSum.totalVal.setText(String.valueOf(Ctm.total));
        Ctm.transSum.payMeth.setText(Ctm.payMeth);
        Ctm.transSum.payMeth1.setText("Cash Returned");
        Ctm.transSum.payMeth1Val.setText(String.valueOf(Ctm.cashRet));
        int Rn = 0;
        for (int i = 0; i < 100; i++) {
            Rn = r.nextInt(10) + 1;
        }
        Ctm.settranID(Rn);
        Ctm.transSum.transIdVal.setText(String.valueOf(Rn));
        Ctm.transSum.setVisible(true);

    }//GEN-LAST:event_continueButtonActionPerformed

    private void cashInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashInsertActionPerformed

    private void cashInsertKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashInsertKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cashInsertKeyTyped

    private void submitCashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCashButtonActionPerformed
        Ctm.cashIns = Integer.parseInt(cashInsert.getText());
        if (Ctm.cashIns < (Ctm.total)) {
            warningLab.setText("Enter a value more than Required Cash");
        } else {

            Ctm.cashRet = (Ctm.cashIns) - (Ctm.total);
            cashReturnVal.setText(String.valueOf(Ctm.cashRet));
        }
    }//GEN-LAST:event_submitCashButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashPayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashPayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashPayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashPayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashPayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountOf;
    private javax.swing.JTextField cashInsert;
    private javax.swing.JLabel cashPayment;
    public javax.swing.JLabel cashReturnVal;
    private javax.swing.JLabel cashReturned;
    private javax.swing.JButton continueButton;
    public javax.swing.JLabel initialAmntCash;
    public javax.swing.JLabel initialCurrLab;
    public javax.swing.JLabel initialCurrLabel;
    private javax.swing.JLabel intialAmntCash;
    private javax.swing.JLabel required;
    private javax.swing.JButton submitCashButton;
    private javax.swing.JLabel warningLab;
    // End of variables declaration//GEN-END:variables
}
