/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ctm;
/**
 *
 * @author harsi
 */
public class selectionFrame extends javax.swing.JFrame {
    /**
     * Creates new form selectionFrame
     */
    public selectionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pound_icon1 = new javax.swing.JLabel();
        peso_icon1 = new javax.swing.JLabel();
        euro_icon1 = new javax.swing.JLabel();
        won_icon1 = new javax.swing.JLabel();
        yen_icon1 = new javax.swing.JLabel();
        selectHeading1 = new javax.swing.JLabel();
        peso_button1 = new javax.swing.JButton();
        euro_button1 = new javax.swing.JButton();
        won_button1 = new javax.swing.JButton();
        cad_icon1 = new javax.swing.JLabel();
        pound_button1 = new javax.swing.JButton();
        cad_button1 = new javax.swing.JButton();
        yen_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pound_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctm/Pound.jpeg"))); // NOI18N

        peso_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctm/Peso.jpeg"))); // NOI18N

        euro_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctm/Euro.jpeg"))); // NOI18N

        won_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctm/Won.jpeg"))); // NOI18N

        yen_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctm/Yen.jpeg"))); // NOI18N

        selectHeading1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        selectHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectHeading1.setText("Select Exchange Currency");
        selectHeading1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        peso_button1.setText("PESO");
        peso_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_button1ActionPerformed(evt);
            }
        });

        euro_button1.setText("EURO");
        euro_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euro_button1ActionPerformed(evt);
            }
        });

        won_button1.setText("WON");
        won_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                won_button1ActionPerformed(evt);
            }
        });

        cad_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctm/CAD.jpeg"))); // NOI18N

        pound_button1.setText("POUND");
        pound_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pound_button1ActionPerformed(evt);
            }
        });

        cad_button1.setText("CAD");
        cad_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_button1ActionPerformed(evt);
            }
        });

        yen_button1.setText("YEN");
        yen_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yen_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectHeading1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pound_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(cad_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(cad_button1)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(won_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(euro_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(euro_button1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peso_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yen_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(peso_button1)
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(pound_button1)
                        .addGap(169, 169, 169)
                        .addComponent(won_button1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yen_button1)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(selectHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cad_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(euro_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(peso_icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso_button1)
                    .addComponent(euro_button1)
                    .addComponent(cad_button1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(won_icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pound_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(yen_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pound_button1)
                    .addComponent(won_button1)
                    .addComponent(yen_button1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cad_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_button1ActionPerformed
         Ctm.conversion.setVisible(true);
          this.setVisible(false);
          Ctm.curr = "CAD";
          Ctm.excRate = 1.37;
          Ctm.conversion.initialCurr.setText(Ctm.curr);
          Ctm.conversion.excCurr.setText(Ctm.convCurr);
          Ctm.conversion.excRate.setText(String.valueOf(Ctm.excRate));
    }//GEN-LAST:event_cad_button1ActionPerformed

    private void euro_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euro_button1ActionPerformed
        Ctm.conversion.setVisible(true);
          this.setVisible(false);
          Ctm.curr = "Euro";
          Ctm.excRate = 0.90;
          Ctm.conversion.initialCurr.setText(Ctm.curr);
          Ctm.conversion.excCurr.setText(Ctm.convCurr);
          Ctm.conversion.excRate.setText(String.valueOf(Ctm.excRate));
    }//GEN-LAST:event_euro_button1ActionPerformed

    private void peso_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_button1ActionPerformed
        Ctm.conversion.setVisible(true);
          this.setVisible(false);
          Ctm.curr = "Peso";
          Ctm.excRate = 17.99;
          Ctm.conversion.initialCurr.setText(Ctm.curr);
          Ctm.conversion.excCurr.setText(Ctm.convCurr);
          Ctm.conversion.excRate.setText(String.valueOf(Ctm.excRate));
    }//GEN-LAST:event_peso_button1ActionPerformed

    private void pound_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pound_button1ActionPerformed
        Ctm.conversion.setVisible(true);
          this.setVisible(false);
          Ctm.curr = "Pound";
          Ctm.excRate = 0.80;
          Ctm.conversion.initialCurr.setText(Ctm.curr);
          Ctm.conversion.excCurr.setText(Ctm.convCurr);
          Ctm.conversion.excRate.setText(String.valueOf(Ctm.excRate));
    }//GEN-LAST:event_pound_button1ActionPerformed

    private void won_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_won_button1ActionPerformed
        Ctm.conversion.setVisible(true);
          this.setVisible(false);
          Ctm.curr = "Won";
          Ctm.excRate = 1330.37;
          Ctm.conversion.initialCurr.setText(Ctm.curr);
          Ctm.conversion.excCurr.setText(Ctm.convCurr);
          Ctm.conversion.excRate.setText(String.valueOf(Ctm.excRate));
    }//GEN-LAST:event_won_button1ActionPerformed

    private void yen_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yen_button1ActionPerformed
        Ctm.conversion.setVisible(true);
        Ctm.curr = "Yen";
        Ctm.excRate = 134.17;
        Ctm.conversion.initialCurr.setText(Ctm.curr);
        Ctm.conversion.excCurr.setText(Ctm.convCurr);
        Ctm.conversion.excRate.setText(String.valueOf(Ctm.excRate));
    }//GEN-LAST:event_yen_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cad_button1;
    private javax.swing.JLabel cad_icon1;
    public javax.swing.JButton euro_button1;
    private javax.swing.JLabel euro_icon1;
    public javax.swing.JButton peso_button1;
    private javax.swing.JLabel peso_icon1;
    public javax.swing.JButton pound_button1;
    private javax.swing.JLabel pound_icon1;
    private javax.swing.JLabel selectHeading1;
    public javax.swing.JButton won_button1;
    private javax.swing.JLabel won_icon1;
    public javax.swing.JButton yen_button1;
    private javax.swing.JLabel yen_icon1;
    // End of variables declaration//GEN-END:variables
}
